# Generated by Django 5.1 on 2024-09-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftCoin', '0002_remove_customuser_is_verified_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
