# Generated by Django 5.1 on 2024-09-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftCoin', '0004_ipaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortURL',
        ),
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
