# Generated by Django 5.1 on 2024-09-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftCoin', '0008_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServersTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='servers-tops/')),
            ],
        ),
    ]
