# Generated by Django 5.1 on 2024-09-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftCoin', '0009_serverstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstop',
            name='ip_address',
            field=models.CharField(max_length=255),
        ),
    ]
