# Generated by Django 5.1 on 2024-09-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftCoin', '0010_alter_serverstop_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstop',
            name='image',
            field=models.ImageField(default=0, upload_to='servers-tops/'),
            preserve_default=False,
        ),
    ]
