# Generated by Django 5.1 on 2024-09-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_modalidad',
            field=models.ImageField(default=1, upload_to='products/modalidad'),
            preserve_default=False,
        ),
    ]
