# Generated by Django 5.1 on 2024-09-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
