# Generated by Django 5.1 on 2024-09-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server1', '0002_serverinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='new-servers/'),
            preserve_default=False,
        ),
    ]
